version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - graphviz
  commands:
    - pip install --upgrade pip
    - pip install -e .
    - sphinx-build -b html docs/source docs/build/html

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true

formats:
  - htmlzip
  - pdf

python:
  install:
    - requirements: docs/requirements.txt
