version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - graphviz
  jobs:
    pre_build:
      - pip install --upgrade pip
      - pip install .

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false
  builder: html

formats:
  - htmlzip
  - pdf
  - epub

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
