version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - graphviz

  jobs:
    pre_build:
      - pip install --upgrade pip
      - pip install -e .
      - pip install sphinx sphinx-rtd-theme sphinx-copybutton myst-parser

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false
  builder: html

formats:
  - htmlzip
  - pdf

python:
  install:
    - requirements: docs/requirements.txt
